### PR TITLE
Bump finatra to 20.5.0 and jackson 2.10

### PR DESCRIPTION
**Pull request by kimxogus**
Jackson 2.11 blocker https://github.com/swagger-api/swagger-core/issues/3554

### CODE REVIEW

**Comment by jakehschwartz** [comment]
@kimxogus Why did you close? Was it not working as expected?

**Comment by mgd43b** [comment]
@jakehschwartz  - Finatra is now using Jackson 2.11 - which I _think_ means this might be more involved, as the io.swagger libs are still on 2.10.1, and they might need upgraded.

**Comment by kimxogus** [comment]
no it wasn't.
with jackson 2.10, it causes exception

**Comment by jakehschwartz** [comment]
Got it, I missed the issue referenced in the original post. Sounds like they are hoping to update it soon, so that's good. In the meantime, I can try to make sure we can move to the new swagger-core repository without issues and then update all the jackson stuff at once

**Comment by jakehschwartz** [comment]
Right which it doesnt because they were on Jackson 2.9 in previous version of Finatra. Fun 🤣

**Pull request closed without merging**
