### PR TITLE
Bump finatra to 20.5.0 and jackson 2.10

### PR DESCRIPTION
**Pull request by kimxogus**
Rework of #48
It seems to be working to me.

Ref https://github.com/swagger-akka-http/swagger-akka-http/commit/da4efc1d0915683592af988300dc4bce2a9b91c7

### CODE REVIEW

**Comment by xcv58** [comment]
+1 for this, we have a Jackson ScalaObjectMapper runtime issue on server starts up and this PR might fix it.

Thanks @kimxogus

**Comment by kimxogus** [comment]
@jakehschwartz Can you tell when this is going to be released?

**Comment by jakehschwartz** [comment]
It takes 24 hours after merging for things to get onto Sonatype. Your version is up now as a SNAPSHOT, figured that would be safest incase there were other issues. Will have time to solidify it this weekend

**Comment by kimxogus** [comment]
For me it's working fine with finatra 20.6.0 and finatra-swagger 20.5.0-SNAPSHOT

**Pull request merged**
