### PR TITLE
update finagle stack

### PR DESCRIPTION
**Pull request by viktortnk**
`FileResolver` does not longer exist in newer version of Finagle stack. I've ported related code and removed dependency of it from DocsController

All of it running well in Whisk

### CODE REVIEW

**Comment by mikeki** [comment]
@jakehschwartz Any plans to merge this?

**Comment by jakehschwartz** [comment]
Hey @mikeki and @viktortnk ,

Sorry, I didnt get an email for the initial PR, just for the comment. I will take a look at this sometime this week, by this weekend at the very latest.

**Comment by mikeki** [comment]
Thank you @jakehschwartz, don't worry that's why I made the comment :)

**Comment by mikeki** [comment]
Friendly reminder :) thanks!

**Comment by jakehschwartz** [comment]
@mikeki, @viktortnk : Version 17.11.0 is now in maven central. Enjoy!

**Comment by mikeki** [comment]
Thank you @jakehschwartz !

**Pull request merged**
